title: Carthographers

screen:
  # screen has no position
  size: [1000, 800]
  color: [255, 255, 255]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: -1
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255

map:
  position: [30, 30]
  # map size is determined by field size
  color: [255, 255, 255]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: 2
  frame_color: [0, 0, 0]
  frame_rounding: 0
  padding: 2
  opacity: 255

option:
  position: [50, 420]
  size: [150, 180]
  color: [255, 255, 255]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: 1
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255
  spacing: 20
  shape_offset: [15, 15]
  candidate_frame_width: 3
  candidate_frame_color: [0, 0, 0]
  coin:
    offset: [65, 150]
    size: [20, 20]
    color: [255, 215, 0]
    image: null
    image_size: null
    image_offset: [0, 0]
    frame_width: 2
    frame_color: [0, 0, 0]
    frame_rounding: 0
    opacity: 255

single_option:
  position: [50, 620]
  size: [60, 60]
  color: [255, 255, 255]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: 1
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255
  spacing: 20
  shape_offset: [15, 15]
  candidate_frame_width: 3
  candidate_frame_color: [0, 0, 0]
  
field:
  size: 30
  colors:
    village: [204, 24, 24]
    water: [47, 32, 179]
    forest: [10, 120, 10]
    farm: [245, 172, 2]
    monster: [122, 16, 143]
    empty: [219, 175, 132]
    mountain: [104, 108, 110]
    waste: [92, 92, 54]
  images:
    village: null #"house.png"
    water: null #"water.png"
    forest: null #"tree.png"
    farm: null #"field.png"
    monster: null #"monster.png"
    empty: null #"empty.png"
    mountain: null #"mountain.png"
    waste: null
  image_size: [20, 20]
  image_offset: [5, 5]
  frame_width: 1
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255
  candidate_opacity: 150
  ruin_overlay: "ruin_icon.png"

candidate:
  opacity: 150
  frame_width: 3
  frame_color: [0, 0, 0]
  opacity_setable: 200
  frame_width_setable: 3
  frame_color_setable: [0, 0, 0]

next_button:
  position: [500, 400]
  size: [90, 60]
  color: [0, 255, 0]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: 2
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255
  text: "Next"
  text_font: "comicsansms"
  text_size: 30
  text_color: [0, 0, 0]
  text_offset: [10, 10]

options_background:
  position: [30, 400]
  size: [420, 300]
  color: [255, 255, 255]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: 1
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255

score_table:
  position: [400, 30]
  size: [600, 300]
  color: [255, 255, 255]
  image: null
  image_size: null
  image_offset: [0, 0]
  frame_width: 1
  frame_color: [0, 0, 0]
  frame_rounding: 0
  opacity: 255
  table_offset: [10, 10]
  font: comicsansms
  font_size: 20
  font_color: [0, 0, 0]
  table_frame_color: [0, 0, 0]
  table_frame_width: 3
  table_frame_rounding: 0
  col_names: ["", " Spring ", " Summer ", " Autumn ", " Winter ", " Total "]
  row_names: ["", " Option Coins ", " Surrounded Mountains ", " Monsters ", " Task A ", " Task B "]
